const assert = require('assert');
const { instanceStatusCache } = require('../tools/instance-status-cache');
let now = 100000;
const cache = instanceStatusCache(() => now);
assert.equal(cache.get('host', ['one'])[0].stale, true);
cache.record('host', ['one'], [{ instanceId: 'one', observedAt: new Date(now).toISOString(), state: 'active', pid: 12, loaded: true }, { instanceId: 'foreign', observedAt: new Date(now).toISOString(), state: 'active' }]);
assert.equal(cache.get('host', ['one'])[0].stale, false);
cache.record('host', ['one'], [{ instanceId: 'one', observedAt: new Date(now - 1000).toISOString(), state: 'inactive' }]);
assert.equal(cache.get('host', ['one'])[0].state, 'active');
now += 16000;
assert.equal(cache.get('host', ['one'])[0].stale, true);
assert.equal(cache.get('other-host', ['one'])[0].state, 'unknown');
assert.equal(cache.get('host', ['foreign'])[0].state, 'unknown');
now = 200000;
cache.record('host', ['one'], [{ instanceId: 'one', observedAt: new Date(now).toISOString(), state: 'active', pid: 20, loaded: true, telemetry: { source: 'ipc', lifecycle: 'READY', lifecycleReason: 'LISTENING', tcpLogicalUp: 1000, tcpLogicalDown: 2000, udpLogicalUp: 20, udpLogicalDown: 30, cpuPercent: 1.2, endpoint: 'secret' } }]);
now += 5000;
cache.record('host', ['one'], [{ instanceId: 'one', observedAt: new Date(now).toISOString(), state: 'active', pid: 20, loaded: true, telemetry: { source: 'ipc', lifecycle: 'READY', tcpLogicalUp: 2020, tcpLogicalDown: 4030, udpLogicalUp: 0, udpLogicalDown: 0 } }]);
let sample = cache.get('host', ['one'])[0];
assert.equal(sample.telemetry.upBytesPerSecond, 200);
assert.equal(sample.telemetry.downBytesPerSecond, 400);
assert.equal(sample.telemetry.endpoint, undefined);
now += 5000;
cache.record('host', ['one'], [{ instanceId: 'one', observedAt: new Date(now).toISOString(), state: 'active', pid: 21, loaded: true, telemetry: { source: 'checkpoint', tcpLogicalUp: 50, tcpLogicalDown: 70, udpLogicalUp: 0, udpLogicalDown: 0 } }]);
sample = cache.get('host', ['one'])[0];
assert.equal(sample.telemetry.upBytesPerSecond, undefined);
assert.equal(sample.telemetry.source, 'checkpoint');
now += 5000;
cache.record('host', ['one'], [{ instanceId: 'one', observedAt: new Date(now).toISOString(), state: 'active', pid: 30, loaded: true, telemetry: { source: 'systemd', cpuUsageNs: 1000000000, rssBytes: 32000000 } }]);
now += 5000;
cache.record('host', ['one'], [{ instanceId: 'one', observedAt: new Date(now).toISOString(), state: 'active', pid: 30, loaded: true, telemetry: { source: 'systemd', cpuUsageNs: 1250000000, rssBytes: 33000000 } }]);
sample = cache.get('host', ['one'])[0];
assert.equal(sample.telemetry.cpuPercent, 5);
assert.equal(sample.telemetry.rssBytes, 33000000);
console.log('status cache stale / ordering / host isolation / telemetry rate reset passed');
