const assert = require('assert');
const { instanceStatusCache } = require('../tools/instance-status-cache');
let now = 100000;
const cache = instanceStatusCache(() => now);
assert.equal(cache.get('host', ['one'])[0].stale, true);
cache.record('host', ['one'], [{ instanceId: 'one', observedAt: new Date(now).toISOString(), state: 'active', pid: 12, loaded: true }, { instanceId: 'foreign', observedAt: new Date(now).toISOString(), state: 'active' }]);
assert.equal(cache.get('host', ['one'])[0].stale, false);
cache.record('host', ['one'], [{ instanceId: 'one', observedAt: new Date(now - 1000).toISOString(), state: 'inactive' }]);
assert.equal(cache.get('host', ['one'])[0].state, 'active');
now += 16000;
assert.equal(cache.get('host', ['one'])[0].stale, true);
assert.equal(cache.get('other-host', ['one'])[0].state, 'unknown');
assert.equal(cache.get('host', ['foreign'])[0].state, 'unknown');

now = 200000;
cache.record('host', ['one'], [{ instanceId: 'one', observedAt: new Date(now).toISOString(), state: 'active', pid: 20, loaded: true, telemetry: { source: 'local', lifecycle: 'READY', lifecycleReason: 'LISTENING', uptimeMs: 10000, tcpLogicalUp: '1000', tcpLogicalDown: '2000', udpLogicalUp: '20', udpLogicalDown: '30', cpuPercent: 1.2, version: '2.0.2', serviceEndpoint: '*:2077', configSummary: 'listen=*:2077 tls=1' } }]);
now += 5000;
cache.record('host', ['one'], [{ instanceId: 'one', observedAt: new Date(now).toISOString(), state: 'active', pid: 20, loaded: true, telemetry: { source: 'local', lifecycle: 'READY', uptimeMs: 15000, tcpLogicalUp: '2020', tcpLogicalDown: '4030', udpLogicalUp: '0', udpLogicalDown: '0', version: '2.0.2', serviceEndpoint: '*:2077', configSummary: 'listen=*:2077 tls=1' } }]);
let sample = cache.get('host', ['one'])[0];
assert.equal(sample.telemetry.upBytesPerSecond, 200);
assert.equal(sample.telemetry.downBytesPerSecond, 400);
assert.equal(sample.telemetry.serviceEndpoint, '*:2077');
assert.equal(sample.telemetry.tcpLogicalUp, '2020');
now += 5000;
cache.record('host', ['one'], [{ instanceId: 'one', observedAt: new Date(now).toISOString(), state: 'active', pid: 21, loaded: true, telemetry: { source: 'unavailable' } }]);
sample = cache.get('host', ['one'])[0];
assert.equal(sample.telemetry.upBytesPerSecond, undefined);
assert.equal(sample.telemetry.source, 'unavailable');

now += 5000;
cache.record('host', ['one'], [{ instanceId: 'one', observedAt: new Date(now).toISOString(), state: 'active', pid: 30, loaded: true, telemetry: { source: 'systemd', cpuUsageNs: 1000000000, rssBytes: 32000000 } }]);
now += 5000;
cache.record('host', ['one'], [{ instanceId: 'one', observedAt: new Date(now).toISOString(), state: 'active', pid: 30, loaded: true, telemetry: { source: 'systemd', cpuUsageNs: 1250000000, rssBytes: 33000000 } }]);
sample = cache.get('host', ['one'])[0];
assert.equal(sample.telemetry.cpuPercent, 5);
assert.equal(sample.telemetry.rssBytes, 33000000);
console.log('status cache stale / uptime-derived rates / lossless counters / reset passed');
