const assert = require('assert');
const { spawnSync } = require('child_process');
const { buildInstanceStatus, buildServiceStatus } = require('../tools/instance-status');
const command = buildInstanceStatus([{ id: 'nw-test001', kind: 'nowhere' }, { id: 'sb-test002', kind: 'sing-box' }]);
const parts = [...command.matchAll(/'([^']+)'/g)].map(item => item[1]);
const script = Buffer.from(parts[1], 'base64').toString();
const mock = `import subprocess,types,json\ncalls=[]\ndef fake(args,**kwargs):\n calls.append(args)\n if args[0]=='systemctl':\n  assert len(args)==6\n  return types.SimpleNamespace(stdout='Id=proxy-console-nowhere@nw-test001.service\\nLoadState=loaded\\nActiveState=active\\nSubState=running\\nMainPID=42\\n',returncode=0)\n if args[0]=='nsenter':\n  payload={'tcp_logical_up':1000,'tcp_logical_down':2000,'udp_logical_up':20,'udp_logical_down':30,'cpu_percent':1.5,'lifecycle':'READY','lifecycle_reason':'LISTENING','endpoint':'secret'}\n  return types.SimpleNamespace(stdout=json.dumps(payload),returncode=0)\n raise AssertionError(args)\nsubprocess.run=fake\n`;
const result = spawnSync('python3', ['-c', "import shutil\nshutil.which=lambda name:'/usr/bin/nsenter'\n" + mock + script, parts[2]], { encoding: 'utf8' });
assert.equal(result.status, 0, result.stderr);
const states = JSON.parse(Buffer.from(result.stdout.trim().split('\t')[2], 'base64')).states;
assert.equal(states[0].state, 'active'); assert.equal(states[0].pid, 42);
assert.equal(states[0].telemetry.source, 'ipc');
assert.equal(states[0].telemetry.tcpLogicalUp, 1000);
assert.equal(states[0].telemetry.lifecycle, 'READY');
assert.equal(states[0].telemetry.endpoint, undefined);
assert.equal(states[1].state, 'unknown'); assert.equal(states[1].loaded, false);
assert(states.every(row => !Number.isNaN(Date.parse(row.observedAt))));
assert(script.includes("entry['address'].rsplit(':',1)"));
assert(script.includes("ipaddress.ip_address(host).is_loopback"));
assert(script.includes("descriptor.get('protocol_version')!=2"));
assert(script.includes("'source': 'unavailable'"));
assert(!script.includes("clean['endpoint']"));
assert(!script.includes("clean['config_summary']"));
assert.throws(() => buildInstanceStatus([{ id: '../other', kind: 'nowhere' }]));
const serviceCommand = buildServiceStatus();
const serviceParts = [...serviceCommand.matchAll(/'([^']+)'/g)].map(item => item[1]);
const serviceTargets = JSON.parse(Buffer.from(serviceParts[2], 'base64'));
assert.deepEqual(serviceTargets.map(item => item.unit), ['sing-box.service', 'nowhere.service']);
console.log('batched instance status: process state plus redacted Nowhere IPC/fallback reader passed');
